/**
 * AUTOGENERATED. Do not edit by hand.
 *
 * Source:      https://hagopianink.wpengine.com
 * Fetched at:  2026-05-13T14:05:02.292Z
 * Manifest v:  1
 *
 * Regenerate with: `jab generate <project-dir>`
 */

/* eslint-disable */
/* tslint:disable */

import type { JabClient, JabRequestOptions } from "./client";
import type {
  GetCategoriesInput,
  GetCategoriesOutput,
  GetExpertiseTagsInput,
  GetExpertiseTagsOutput,
  GetMenusOutput,
  GetOurWorkInput,
  GetOurWorkOutput,
  GetPageBySlugInput,
  GetPageBySlugOutput,
  GetPagesInput,
  GetPagesOutput,
  GetPostBySlugInput,
  GetPostBySlugOutput,
  GetPostsInput,
  GetPostsOutput,
  GetTagsInput,
  GetTagsOutput,
  GetWorkTypeInput,
  GetWorkTypeOutput,
  GetWorksBySlugInput,
  GetWorksBySlugOutput,
} from "./types";

/**
 * Calls the `jab/get-posts` ability.
 */
export async function getPosts(
  client: JabClient,
  input: GetPostsInput = {},
  requestOptions?: JabRequestOptions,
): Promise<GetPostsOutput> {
  return client.callAbility<GetPostsInput, GetPostsOutput>(
    "jab/get-posts",
    input,
    requestOptions,
  );
}

/**
 * Calls the `jab/get-post-by-slug` ability.
 */
export async function getPostBySlug(
  client: JabClient,
  input: GetPostBySlugInput,
  requestOptions?: JabRequestOptions,
): Promise<GetPostBySlugOutput> {
  return client.callAbility<GetPostBySlugInput, GetPostBySlugOutput>(
    "jab/get-post-by-slug",
    input,
    requestOptions,
  );
}

/**
 * Calls the `jab/get-pages` ability.
 */
export async function getPages(
  client: JabClient,
  input: GetPagesInput = {},
  requestOptions?: JabRequestOptions,
): Promise<GetPagesOutput> {
  return client.callAbility<GetPagesInput, GetPagesOutput>(
    "jab/get-pages",
    input,
    requestOptions,
  );
}

/**
 * Calls the `jab/get-page-by-slug` ability.
 */
export async function getPageBySlug(
  client: JabClient,
  input: GetPageBySlugInput,
  requestOptions?: JabRequestOptions,
): Promise<GetPageBySlugOutput> {
  return client.callAbility<GetPageBySlugInput, GetPageBySlugOutput>(
    "jab/get-page-by-slug",
    input,
    requestOptions,
  );
}

/**
 * Calls the `jab/get-our-work` ability.
 */
export async function getOurWork(
  client: JabClient,
  input: GetOurWorkInput = {},
  requestOptions?: JabRequestOptions,
): Promise<GetOurWorkOutput> {
  return client.callAbility<GetOurWorkInput, GetOurWorkOutput>(
    "jab/get-our-work",
    input,
    requestOptions,
  );
}

/**
 * Calls the `jab/get-works-by-slug` ability.
 */
export async function getWorksBySlug(
  client: JabClient,
  input: GetWorksBySlugInput,
  requestOptions?: JabRequestOptions,
): Promise<GetWorksBySlugOutput> {
  return client.callAbility<GetWorksBySlugInput, GetWorksBySlugOutput>(
    "jab/get-works-by-slug",
    input,
    requestOptions,
  );
}

/**
 * Calls the `jab/get-categories` ability.
 *
 * @taxonomy category — CPT-list rows key per-post terms by this slug, which may differ from this ability's wrapper key.
 */
export async function getCategories(
  client: JabClient,
  input: GetCategoriesInput = {},
  requestOptions?: JabRequestOptions,
): Promise<GetCategoriesOutput> {
  return client.callAbility<GetCategoriesInput, GetCategoriesOutput>(
    "jab/get-categories",
    input,
    requestOptions,
  );
}

/**
 * Calls the `jab/get-tags` ability.
 *
 * @taxonomy post_tag — CPT-list rows key per-post terms by this slug, which may differ from this ability's wrapper key.
 */
export async function getTags(
  client: JabClient,
  input: GetTagsInput = {},
  requestOptions?: JabRequestOptions,
): Promise<GetTagsOutput> {
  return client.callAbility<GetTagsInput, GetTagsOutput>(
    "jab/get-tags",
    input,
    requestOptions,
  );
}

/**
 * Calls the `jab/get-expertise-tags` ability.
 *
 * @taxonomy expertise-tag — CPT-list rows key per-post terms by this slug, which may differ from this ability's wrapper key.
 */
export async function getExpertiseTags(
  client: JabClient,
  input: GetExpertiseTagsInput = {},
  requestOptions?: JabRequestOptions,
): Promise<GetExpertiseTagsOutput> {
  return client.callAbility<GetExpertiseTagsInput, GetExpertiseTagsOutput>(
    "jab/get-expertise-tags",
    input,
    requestOptions,
  );
}

/**
 * Calls the `jab/get-work-type` ability.
 *
 * @taxonomy work — CPT-list rows key per-post terms by this slug, which may differ from this ability's wrapper key.
 */
export async function getWorkType(
  client: JabClient,
  input: GetWorkTypeInput = {},
  requestOptions?: JabRequestOptions,
): Promise<GetWorkTypeOutput> {
  return client.callAbility<GetWorkTypeInput, GetWorkTypeOutput>(
    "jab/get-work-type",
    input,
    requestOptions,
  );
}

/**
 * Calls the `jab/get-menus` ability.
 */
export async function getMenus(
  client: JabClient,
  requestOptions?: JabRequestOptions,
): Promise<GetMenusOutput> {
  return client.callAbility<Record<string, never>, GetMenusOutput>(
    "jab/get-menus",
    undefined,
    requestOptions,
  );
}
