/**
 * AUTOGENERATED. Do not edit by hand.
 *
 * Source:      https://hagopian-ink.local
 * Fetched at:  2026-05-11T14:46:39.293Z
 * Manifest v:  1
 *
 * Regenerate with: `jab generate <project-dir>`
 */

/* eslint-disable */
/* tslint:disable */

import type { JabClient } from "./client";
import type {
  GetCategoriesInput,
  GetCategoriesOutput,
  GetMenusOutput,
  GetOurWorkInput,
  GetOurWorkOutput,
  GetPageBySlugInput,
  GetPageBySlugOutput,
  GetPagesInput,
  GetPagesOutput,
  GetPostBySlugInput,
  GetPostBySlugOutput,
  GetPostsInput,
  GetPostsOutput,
  GetTagsInput,
  GetTagsOutput,
  GetWorkTypeInput,
  GetWorkTypeOutput,
  GetWorksBySlugInput,
  GetWorksBySlugOutput,
} from "./types";

/** Calls the `jab/get-posts` ability. */
export async function getPosts(
  client: JabClient,
  input: GetPostsInput = {},
): Promise<GetPostsOutput> {
  return client.callAbility<GetPostsInput, GetPostsOutput>(
    "jab/get-posts",
    input,
  );
}

/** Calls the `jab/get-post-by-slug` ability. */
export async function getPostBySlug(
  client: JabClient,
  input: GetPostBySlugInput,
): Promise<GetPostBySlugOutput> {
  return client.callAbility<GetPostBySlugInput, GetPostBySlugOutput>(
    "jab/get-post-by-slug",
    input,
  );
}

/** Calls the `jab/get-pages` ability. */
export async function getPages(
  client: JabClient,
  input: GetPagesInput = {},
): Promise<GetPagesOutput> {
  return client.callAbility<GetPagesInput, GetPagesOutput>(
    "jab/get-pages",
    input,
  );
}

/** Calls the `jab/get-page-by-slug` ability. */
export async function getPageBySlug(
  client: JabClient,
  input: GetPageBySlugInput,
): Promise<GetPageBySlugOutput> {
  return client.callAbility<GetPageBySlugInput, GetPageBySlugOutput>(
    "jab/get-page-by-slug",
    input,
  );
}

/** Calls the `jab/get-our-work` ability. */
export async function getOurWork(
  client: JabClient,
  input: GetOurWorkInput = {},
): Promise<GetOurWorkOutput> {
  return client.callAbility<GetOurWorkInput, GetOurWorkOutput>(
    "jab/get-our-work",
    input,
  );
}

/** Calls the `jab/get-works-by-slug` ability. */
export async function getWorksBySlug(
  client: JabClient,
  input: GetWorksBySlugInput,
): Promise<GetWorksBySlugOutput> {
  return client.callAbility<GetWorksBySlugInput, GetWorksBySlugOutput>(
    "jab/get-works-by-slug",
    input,
  );
}

/** Calls the `jab/get-categories` ability. */
export async function getCategories(
  client: JabClient,
  input: GetCategoriesInput = {},
): Promise<GetCategoriesOutput> {
  return client.callAbility<GetCategoriesInput, GetCategoriesOutput>(
    "jab/get-categories",
    input,
  );
}

/** Calls the `jab/get-tags` ability. */
export async function getTags(
  client: JabClient,
  input: GetTagsInput = {},
): Promise<GetTagsOutput> {
  return client.callAbility<GetTagsInput, GetTagsOutput>(
    "jab/get-tags",
    input,
  );
}

/** Calls the `jab/get-work-type` ability. */
export async function getWorkType(
  client: JabClient,
  input: GetWorkTypeInput = {},
): Promise<GetWorkTypeOutput> {
  return client.callAbility<GetWorkTypeInput, GetWorkTypeOutput>(
    "jab/get-work-type",
    input,
  );
}

/** Calls the `jab/get-menus` ability. */
export async function getMenus(client: JabClient): Promise<GetMenusOutput> {
  return client.callAbility<Record<string, never>, GetMenusOutput>(
    "jab/get-menus",
  );
}
