/**
 * AUTOGENERATED. Do not edit by hand.
 *
 * Source:      https://hagopianink.wpengine.com
 * Fetched at:  2026-05-13T14:05:02.292Z
 * Manifest v:  1
 * Abilities:   11
 *
 * Regenerate with: `jab generate <project-dir>`
 */

/* eslint-disable */
/* tslint:disable */
// jab/get-posts — Get Posts
/** Retrieves entries from the post post type as id, title, excerpt, date, slug, link, and (when ACF fields apply) acf. */
export interface GetPostsInput {
  /**
   * Number of posts to return.
   */
  numberposts?: number;
  /**
   * Post status filter.
   */
  post_status?: "publish" | "draft" | "any";
}

export interface GetPostsOutput {
  posts: {
    id: number;
    title: string;
    excerpt: string;
    /**
     * Published date in RFC3339 (UTC).
     */
    date: string;
    slug: string;
    link: string;
    featured_image: {
      ID: number;
      url: string;
      alt: string;
      width: number;
      height: number;
    } | null;
    category: {
      id: number;
      name: string;
      slug: string;
      description: string;
      count: number;
      /**
       * 0 for top-level terms; parent term_id otherwise.
       */
      parent_id: number;
    }[];
    post_tag: {
      id: number;
      name: string;
      slug: string;
      description: string;
      count: number;
      /**
       * 0 for top-level terms; parent term_id otherwise.
       */
      parent_id: number;
    }[];
    acf: {
      /**
       * Post Builder
       */
      post_builder?: (
        | {
            /**
             * Full Width Column WYSIWYG
             */
            acf_fc_layout: "full_width_column_wysiwyg";
            /**
             * WYSIWYG
             */
            wysiwyg?: string;
            /**
             * Padding
             */
            padding?: "default-padding" | "extra-padding";
          }
        | {
            /**
             * 2 Column WYSIWYG
             */
            acf_fc_layout: "2_column_wysiwyg";
            /**
             * Column Left Content
             */
            column_left_content?: string;
            /**
             * Column Right Content
             */
            column_right_content?: string;
            /**
             * Padding
             */
            padding?: "default-padding" | "extra-padding";
          }
        | {
            /**
             * 3 Column WYSIWYG
             */
            acf_fc_layout: "3_column_wysiwyg";
            /**
             * Column Left Content
             */
            column_left_content?: string;
            /**
             * Column Center Content
             */
            column_center_content?: string;
            /**
             * Column Right Content
             */
            column_right_content?: string;
            /**
             * Padding
             */
            padding?: "default-padding" | "extra-padding";
          }
        | {
            /**
             * 1/3 Pull Quote + 2/3 WYSIWYG
             */
            acf_fc_layout: "13_pull_quote_23_wysiwyg";
            /**
             * Pull Quote Left
             */
            pull_quote_left?: string;
            /**
             * Column Right Content
             */
            column_right_content?: string;
            /**
             * Padding
             */
            padding?: "default-padding" | "extra-padding";
          }
        | {
            /**
             * Large Pull Quote
             */
            acf_fc_layout: "large_pull_quote";
            /**
             * Pull Quote
             */
            pull_quote?: string;
            /**
             * Quote Author
             */
            quote_author?: string;
            /**
             * Padding
             */
            padding?: "default-padding" | "extra-padding";
          }
        | {
            /**
             * Images Side by Side
             */
            acf_fc_layout: "images_side_by_side";
            /**
             * Image Left
             */
            image_left?: {
              ID?: number;
              id?: number;
              url?: string;
              alt?: string;
              title?: string;
              caption?: string;
              description?: string;
              filename?: string;
              mime_type?: string;
              width?: number;
              height?: number;
              /**
               * Map of registered image-size slug -> URL (and -width / -height keys per size).
               */
              sizes?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            /**
             * Image Right
             */
            image_right?: {
              ID?: number;
              id?: number;
              url?: string;
              alt?: string;
              title?: string;
              caption?: string;
              description?: string;
              filename?: string;
              mime_type?: string;
              width?: number;
              height?: number;
              /**
               * Map of registered image-size slug -> URL (and -width / -height keys per size).
               */
              sizes?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            /**
             * Caption
             */
            caption?: string;
            /**
             * Padding
             */
            padding?: "default-padding" | "extra-padding";
          }
        | {
            /**
             * Image with Caption
             */
            acf_fc_layout: "image_with_caption";
            /**
             * Image
             */
            image?: {
              ID?: number;
              id?: number;
              url?: string;
              alt?: string;
              title?: string;
              caption?: string;
              description?: string;
              filename?: string;
              mime_type?: string;
              width?: number;
              height?: number;
              /**
               * Map of registered image-size slug -> URL (and -width / -height keys per size).
               */
              sizes?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            /**
             * Caption
             */
            caption?: string;
            /**
             * Padding
             */
            padding?: "default-padding" | "extra-padding";
          }
      )[];
      /**
       * Featured Image One — Optional banner image must be in 16:9 aspect ratio.
       */
      journal_post_banner?: {
        ID?: number;
        id?: number;
        url?: string;
        alt?: string;
        title?: string;
        caption?: string;
        description?: string;
        filename?: string;
        mime_type?: string;
        width?: number;
        height?: number;
        /**
         * Map of registered image-size slug -> URL (and -width / -height keys per size).
         */
        sizes?: {
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      /**
       * Featured Image Two
       */
      featured_image_two?: {
        ID?: number;
        id?: number;
        url?: string;
        alt?: string;
        title?: string;
        caption?: string;
        description?: string;
        filename?: string;
        mime_type?: string;
        width?: number;
        height?: number;
        /**
         * Map of registered image-size slug -> URL (and -width / -height keys per size).
         */
        sizes?: {
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      /**
       * Subtitle — Optional subtitle text. Ideally 110 characters or less (can fit in a tweet)
       */
      journal_post_subtitle?: string;
      /**
       * Short Title — Short descriptive title for use in previews, navigation, etc. Ideal ~40 chrs, Max 70 chrs.
       */
      journal_short_title?: string;
      /**
       * Short Description — Short description text for use in previews, navigation etc. Max 80 characters.
       */
      journal_short_desc?: string;
    };
  }[];
}

// jab/get-post-by-slug — Get Post By Slug
/** Retrieves a single post by its slug. Returns the same per-item shape as the list ability for this post type, or null when nothing matches. */
export interface GetPostBySlugInput {
  /**
   * Slug of the post to retrieve.
   */
  slug: string;
  /**
   * Post status filter.
   */
  post_status?: "publish" | "draft" | "any";
}

export interface GetPostBySlugOutput {
  post: {
    id: number;
    title: string;
    excerpt: string;
    /**
     * Published date in RFC3339 (UTC).
     */
    date: string;
    slug: string;
    link: string;
    featured_image: {
      ID: number;
      url: string;
      alt: string;
      width: number;
      height: number;
    } | null;
    category: {
      id: number;
      name: string;
      slug: string;
      description: string;
      count: number;
      /**
       * 0 for top-level terms; parent term_id otherwise.
       */
      parent_id: number;
    }[];
    post_tag: {
      id: number;
      name: string;
      slug: string;
      description: string;
      count: number;
      /**
       * 0 for top-level terms; parent term_id otherwise.
       */
      parent_id: number;
    }[];
    acf: {
      /**
       * Post Builder
       */
      post_builder?: (
        | {
            /**
             * Full Width Column WYSIWYG
             */
            acf_fc_layout: "full_width_column_wysiwyg";
            /**
             * WYSIWYG
             */
            wysiwyg?: string;
            /**
             * Padding
             */
            padding?: "default-padding" | "extra-padding";
          }
        | {
            /**
             * 2 Column WYSIWYG
             */
            acf_fc_layout: "2_column_wysiwyg";
            /**
             * Column Left Content
             */
            column_left_content?: string;
            /**
             * Column Right Content
             */
            column_right_content?: string;
            /**
             * Padding
             */
            padding?: "default-padding" | "extra-padding";
          }
        | {
            /**
             * 3 Column WYSIWYG
             */
            acf_fc_layout: "3_column_wysiwyg";
            /**
             * Column Left Content
             */
            column_left_content?: string;
            /**
             * Column Center Content
             */
            column_center_content?: string;
            /**
             * Column Right Content
             */
            column_right_content?: string;
            /**
             * Padding
             */
            padding?: "default-padding" | "extra-padding";
          }
        | {
            /**
             * 1/3 Pull Quote + 2/3 WYSIWYG
             */
            acf_fc_layout: "13_pull_quote_23_wysiwyg";
            /**
             * Pull Quote Left
             */
            pull_quote_left?: string;
            /**
             * Column Right Content
             */
            column_right_content?: string;
            /**
             * Padding
             */
            padding?: "default-padding" | "extra-padding";
          }
        | {
            /**
             * Large Pull Quote
             */
            acf_fc_layout: "large_pull_quote";
            /**
             * Pull Quote
             */
            pull_quote?: string;
            /**
             * Quote Author
             */
            quote_author?: string;
            /**
             * Padding
             */
            padding?: "default-padding" | "extra-padding";
          }
        | {
            /**
             * Images Side by Side
             */
            acf_fc_layout: "images_side_by_side";
            /**
             * Image Left
             */
            image_left?: {
              ID?: number;
              id?: number;
              url?: string;
              alt?: string;
              title?: string;
              caption?: string;
              description?: string;
              filename?: string;
              mime_type?: string;
              width?: number;
              height?: number;
              /**
               * Map of registered image-size slug -> URL (and -width / -height keys per size).
               */
              sizes?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            /**
             * Image Right
             */
            image_right?: {
              ID?: number;
              id?: number;
              url?: string;
              alt?: string;
              title?: string;
              caption?: string;
              description?: string;
              filename?: string;
              mime_type?: string;
              width?: number;
              height?: number;
              /**
               * Map of registered image-size slug -> URL (and -width / -height keys per size).
               */
              sizes?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            /**
             * Caption
             */
            caption?: string;
            /**
             * Padding
             */
            padding?: "default-padding" | "extra-padding";
          }
        | {
            /**
             * Image with Caption
             */
            acf_fc_layout: "image_with_caption";
            /**
             * Image
             */
            image?: {
              ID?: number;
              id?: number;
              url?: string;
              alt?: string;
              title?: string;
              caption?: string;
              description?: string;
              filename?: string;
              mime_type?: string;
              width?: number;
              height?: number;
              /**
               * Map of registered image-size slug -> URL (and -width / -height keys per size).
               */
              sizes?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            /**
             * Caption
             */
            caption?: string;
            /**
             * Padding
             */
            padding?: "default-padding" | "extra-padding";
          }
      )[];
      /**
       * Featured Image One — Optional banner image must be in 16:9 aspect ratio.
       */
      journal_post_banner?: {
        ID?: number;
        id?: number;
        url?: string;
        alt?: string;
        title?: string;
        caption?: string;
        description?: string;
        filename?: string;
        mime_type?: string;
        width?: number;
        height?: number;
        /**
         * Map of registered image-size slug -> URL (and -width / -height keys per size).
         */
        sizes?: {
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      /**
       * Featured Image Two
       */
      featured_image_two?: {
        ID?: number;
        id?: number;
        url?: string;
        alt?: string;
        title?: string;
        caption?: string;
        description?: string;
        filename?: string;
        mime_type?: string;
        width?: number;
        height?: number;
        /**
         * Map of registered image-size slug -> URL (and -width / -height keys per size).
         */
        sizes?: {
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      /**
       * Subtitle — Optional subtitle text. Ideally 110 characters or less (can fit in a tweet)
       */
      journal_post_subtitle?: string;
      /**
       * Short Title — Short descriptive title for use in previews, navigation, etc. Ideal ~40 chrs, Max 70 chrs.
       */
      journal_short_title?: string;
      /**
       * Short Description — Short description text for use in previews, navigation etc. Max 80 characters.
       */
      journal_short_desc?: string;
    };
  } | null;
}

// jab/get-pages — Get Pages
/** Retrieves entries from the page post type as id, title, excerpt, date, slug, link, and (when ACF fields apply) acf. */
export interface GetPagesInput {
  /**
   * Number of pages to return.
   */
  numberposts?: number;
  /**
   * Post status filter.
   */
  post_status?: "publish" | "draft" | "any";
}

export interface GetPagesOutput {
  pages: {
    id: number;
    title: string;
    excerpt: string;
    /**
     * Published date in RFC3339 (UTC).
     */
    date: string;
    slug: string;
    link: string;
    featured_image: {
      ID: number;
      url: string;
      alt: string;
      width: number;
      height: number;
    } | null;
    acf: {
      /**
       * Title
       */
      header_title?: string;
      /**
       * Title Mobile
       */
      title_mobile?: string;
      /**
       * Subtitle
       */
      header_subtitle?: string;
      /**
       * Link
       */
      header_link?: {
        title?: string;
        url?: string;
        /**
         * Anchor target (e.g. _blank). May be empty.
         */
        target?: string;
      };
      /**
       * Background image
       */
      header_background_image?: string;
      /**
       * Video ( webm )
       */
      video_webm?: string;
      /**
       * Video ( mp4 )
       */
      video_mp4?: string;
      /**
       * Blocks
       */
      template_part?: (
        | {
            /**
             * Contact form
             */
            acf_fc_layout: "contact-form";
            /**
             * Title
             */
            title?: string;
            /**
             * Subtitle
             */
            subtitle?: string;
            /**
             * Background color
             */
            background_color?: "linear-gradient" | "color";
            /**
             * Text befor contact form
             */
            text_befor_contact_form?: string;
            /**
             * Display form?
             */
            display_form?: "no" | "yes";
            /**
             * Phone
             */
            phone?: string;
            /**
             * Email subject
             */
            email_subject?: string;
            /**
             * Email
             */
            email?: string;
            /**
             * Testimonials
             */
            testimonials?: {
              ID?: number;
              post_title?: string;
              /**
               * URL slug.
               */
              post_name?: string;
              post_type?: string;
              /**
               * WP-format datetime; not RFC3339.
               */
              post_date?: string;
              post_status?: string;
              [k: string]: unknown;
            }[];
          }
        | {
            /**
             * Contact Form Global
             */
            acf_fc_layout: "contact-form-global";
          }
        | {
            /**
             * Subscription Form Global
             */
            acf_fc_layout: "subscription-form-global";
          }
        | {
            /**
             * Subscription form
             */
            acf_fc_layout: "subscription-form";
            /**
             * Title
             */
            title?: string;
            /**
             * Subtitle
             */
            subtitle?: string;
            /**
             * Form ( shortcode )
             */
            form?: string;
            /**
             * Background img
             */
            subscription_form_background_img?: string;
            /**
             * Video ( webm )
             */
            subscription_form_video_webm?: string;
            /**
             * Video ( mp4 )
             */
            subscription_form_video_mp4?: string;
          }
        | {
            /**
             * Our blog
             */
            acf_fc_layout: "our-blog";
            /**
             * Title
             */
            title?: string;
            /**
             * Link
             */
            link?: {
              title?: string;
              url?: string;
              /**
               * Anchor target (e.g. _blank). May be empty.
               */
              target?: string;
            };
          }
        | {
            /**
             * Text bock
             */
            acf_fc_layout: "text-bock";
            /**
             * Title
             */
            title?: string;
            /**
             * Description
             */
            description?: string;
            /**
             * Link
             */
            link?: {
              title?: string;
              url?: string;
              /**
               * Anchor target (e.g. _blank). May be empty.
               */
              target?: string;
            };
            /**
             * Width ( % )
             */
            width?: number;
            /**
             * Background color
             */
            background_color?: "white" | "linear-gradient-dribbble";
          }
        | {
            /**
             * Blocks
             */
            acf_fc_layout: "blocks";
            /**
             * Background color
             */
            "background-color"?: string;
            /**
             * Block
             */
            block?: {
              "name-group"?: {
                /**
                 * name
                 */
                name?: string;
                /**
                 * color
                 */
                color?: string;
              };
              /**
               * title
               */
              title?: string;
              /**
               * description
               */
              description?: string;
              /**
               * link
               */
              link?: {
                title?: string;
                url?: string;
                /**
                 * Anchor target (e.g. _blank). May be empty.
                 */
                target?: string;
              };
              /**
               * img
               */
              img?: string;
              /**
               * icon
               */
              icon?: string;
            }[];
          }
        | {
            /**
             * Our clients
             */
            acf_fc_layout: "our-clients";
            /**
             * Title
             */
            title?: string;
            /**
             * Client
             */
            client?: {
              /**
               * Image
               */
              image?: string;
              /**
               * Link
               */
              link?: {
                title?: string;
                url?: string;
                /**
                 * Anchor target (e.g. _blank). May be empty.
                 */
                target?: string;
              };
            }[];
            /**
             * Slider
             */
            slider?: "no" | "yes";
          }
        | {
            /**
             * Case studies
             */
            acf_fc_layout: "case-studies";
            /**
             * Case
             */
            case?: {
              /**
               * Image
               */
              image?: {
                ID?: number;
                id?: number;
                url?: string;
                alt?: string;
                title?: string;
                caption?: string;
                description?: string;
                filename?: string;
                mime_type?: string;
                width?: number;
                height?: number;
                /**
                 * Map of registered image-size slug -> URL (and -width / -height keys per size).
                 */
                sizes?: {
                  [k: string]: unknown;
                };
                [k: string]: unknown;
              };
              /**
               * Text top
               */
              text_top?: string;
              /**
               * Title
               */
              title?: string;
              /**
               * Description
               */
              description?: string;
              /**
               * Link
               */
              link?: {
                title?: string;
                url?: string;
                /**
                 * Anchor target (e.g. _blank). May be empty.
                 */
                target?: string;
              };
            }[];
            /**
             * Link
             */
            link?: {
              title?: string;
              url?: string;
              /**
               * Anchor target (e.g. _blank). May be empty.
               */
              target?: string;
            };
          }
        | {
            /**
             * Core Values
             */
            acf_fc_layout: "core-values";
            /**
             * Title
             */
            title?: string;
            /**
             * Core Value
             */
            core_value?: {
              /**
               * Title
               */
              title?: string;
              /**
               * Image
               */
              image?: string;
            }[];
          }
        | {
            /**
             * Team
             */
            acf_fc_layout: "team";
            /**
             * Title
             */
            title?: string;
            /**
             * Persons
             */
            persons?: {
              ID?: number;
              post_title?: string;
              /**
               * URL slug.
               */
              post_name?: string;
              post_type?: string;
              /**
               * WP-format datetime; not RFC3339.
               */
              post_date?: string;
              post_status?: string;
              [k: string]: unknown;
            }[];
          }
        | {
            /**
             * Our publications
             */
            acf_fc_layout: "our-publications";
            /**
             * Awards
             */
            awards?: {
              /**
               * Title
               */
              title?: string;
              /**
               * Awards
               */
              content?: string;
            };
            /**
             * PUBLICATIONS
             */
            publications?: {
              /**
               * Title
               */
              title?: string;
              /**
               * PUBLICATIONS
               */
              content?: string;
            };
            /**
             * ARTICLES & FEATURES
             */
            "articles_&_features"?: {
              /**
               * Title
               */
              title?: string;
              /**
               * ARTICLES & FEATURES
               */
              content?: string;
            };
          }
        | {
            /**
             * Expertise
             */
            acf_fc_layout: "expertise";
            /**
             * Title
             */
            title?: string;
            /**
             * Block
             */
            block?: {
              /**
               * Icon
               */
              icon?: {
                ID?: number;
                id?: number;
                url?: string;
                alt?: string;
                title?: string;
                caption?: string;
                description?: string;
                filename?: string;
                mime_type?: string;
                width?: number;
                height?: number;
                /**
                 * Map of registered image-size slug -> URL (and -width / -height keys per size).
                 */
                sizes?: {
                  [k: string]: unknown;
                };
                [k: string]: unknown;
              };
              /**
               * Title
               */
              title?: string;
              /**
               * Description
               */
              description?: string;
            }[];
            /**
             * Link
             */
            link?: {
              title?: string;
              url?: string;
              /**
               * Anchor target (e.g. _blank). May be empty.
               */
              target?: string;
            };
          }
        | {
            /**
             * Mobile pages
             */
            acf_fc_layout: "mobile-pages";
            /**
             * Images
             */
            images?: {
              /**
               * Image
               */
              image?: {
                ID?: number;
                id?: number;
                url?: string;
                alt?: string;
                title?: string;
                caption?: string;
                description?: string;
                filename?: string;
                mime_type?: string;
                width?: number;
                height?: number;
                /**
                 * Map of registered image-size slug -> URL (and -width / -height keys per size).
                 */
                sizes?: {
                  [k: string]: unknown;
                };
                [k: string]: unknown;
              };
            }[];
          }
        | {
            /**
             * Our Work
             */
            acf_fc_layout: "our-work";
            /**
             * Background color
             */
            background_color?: "default" | "linear-gradient-dribbble" | "white";
            name_group?: {
              /**
               * Name
               */
              name?: string;
              /**
               * Color
               */
              color?: string;
            };
            /**
             * Title
             */
            title?: string;
            /**
             * Description
             */
            description?: string;
            /**
             * Link
             */
            link?: {
              title?: string;
              url?: string;
              /**
               * Anchor target (e.g. _blank). May be empty.
               */
              target?: string;
            };
            /**
             * Image
             */
            image?: {
              ID?: number;
              id?: number;
              url?: string;
              alt?: string;
              title?: string;
              caption?: string;
              description?: string;
              filename?: string;
              mime_type?: string;
              width?: number;
              height?: number;
              /**
               * Map of registered image-size slug -> URL (and -width / -height keys per size).
               */
              sizes?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            /**
             * Column reverse
             */
            column_reverse?: "no" | "yes";
          }
        | {
            /**
             * Instagram
             */
            acf_fc_layout: "instagram";
          }
      )[];
    };
  }[];
}

// jab/get-page-by-slug — Get Page By Slug
/** Retrieves a single page by its slug. Returns the same per-item shape as the list ability for this post type, or null when nothing matches. */
export interface GetPageBySlugInput {
  /**
   * Slug of the page to retrieve.
   */
  slug: string;
  /**
   * Post status filter.
   */
  post_status?: "publish" | "draft" | "any";
}

export interface GetPageBySlugOutput {
  page: {
    id: number;
    title: string;
    excerpt: string;
    /**
     * Published date in RFC3339 (UTC).
     */
    date: string;
    slug: string;
    link: string;
    featured_image: {
      ID: number;
      url: string;
      alt: string;
      width: number;
      height: number;
    } | null;
    acf: {
      /**
       * Title
       */
      header_title?: string;
      /**
       * Title Mobile
       */
      title_mobile?: string;
      /**
       * Subtitle
       */
      header_subtitle?: string;
      /**
       * Link
       */
      header_link?: {
        title?: string;
        url?: string;
        /**
         * Anchor target (e.g. _blank). May be empty.
         */
        target?: string;
      };
      /**
       * Background image
       */
      header_background_image?: string;
      /**
       * Video ( webm )
       */
      video_webm?: string;
      /**
       * Video ( mp4 )
       */
      video_mp4?: string;
      /**
       * Blocks
       */
      template_part?: (
        | {
            /**
             * Contact form
             */
            acf_fc_layout: "contact-form";
            /**
             * Title
             */
            title?: string;
            /**
             * Subtitle
             */
            subtitle?: string;
            /**
             * Background color
             */
            background_color?: "linear-gradient" | "color";
            /**
             * Text befor contact form
             */
            text_befor_contact_form?: string;
            /**
             * Display form?
             */
            display_form?: "no" | "yes";
            /**
             * Phone
             */
            phone?: string;
            /**
             * Email subject
             */
            email_subject?: string;
            /**
             * Email
             */
            email?: string;
            /**
             * Testimonials
             */
            testimonials?: {
              ID?: number;
              post_title?: string;
              /**
               * URL slug.
               */
              post_name?: string;
              post_type?: string;
              /**
               * WP-format datetime; not RFC3339.
               */
              post_date?: string;
              post_status?: string;
              [k: string]: unknown;
            }[];
          }
        | {
            /**
             * Contact Form Global
             */
            acf_fc_layout: "contact-form-global";
          }
        | {
            /**
             * Subscription Form Global
             */
            acf_fc_layout: "subscription-form-global";
          }
        | {
            /**
             * Subscription form
             */
            acf_fc_layout: "subscription-form";
            /**
             * Title
             */
            title?: string;
            /**
             * Subtitle
             */
            subtitle?: string;
            /**
             * Form ( shortcode )
             */
            form?: string;
            /**
             * Background img
             */
            subscription_form_background_img?: string;
            /**
             * Video ( webm )
             */
            subscription_form_video_webm?: string;
            /**
             * Video ( mp4 )
             */
            subscription_form_video_mp4?: string;
          }
        | {
            /**
             * Our blog
             */
            acf_fc_layout: "our-blog";
            /**
             * Title
             */
            title?: string;
            /**
             * Link
             */
            link?: {
              title?: string;
              url?: string;
              /**
               * Anchor target (e.g. _blank). May be empty.
               */
              target?: string;
            };
          }
        | {
            /**
             * Text bock
             */
            acf_fc_layout: "text-bock";
            /**
             * Title
             */
            title?: string;
            /**
             * Description
             */
            description?: string;
            /**
             * Link
             */
            link?: {
              title?: string;
              url?: string;
              /**
               * Anchor target (e.g. _blank). May be empty.
               */
              target?: string;
            };
            /**
             * Width ( % )
             */
            width?: number;
            /**
             * Background color
             */
            background_color?: "white" | "linear-gradient-dribbble";
          }
        | {
            /**
             * Blocks
             */
            acf_fc_layout: "blocks";
            /**
             * Background color
             */
            "background-color"?: string;
            /**
             * Block
             */
            block?: {
              "name-group"?: {
                /**
                 * name
                 */
                name?: string;
                /**
                 * color
                 */
                color?: string;
              };
              /**
               * title
               */
              title?: string;
              /**
               * description
               */
              description?: string;
              /**
               * link
               */
              link?: {
                title?: string;
                url?: string;
                /**
                 * Anchor target (e.g. _blank). May be empty.
                 */
                target?: string;
              };
              /**
               * img
               */
              img?: string;
              /**
               * icon
               */
              icon?: string;
            }[];
          }
        | {
            /**
             * Our clients
             */
            acf_fc_layout: "our-clients";
            /**
             * Title
             */
            title?: string;
            /**
             * Client
             */
            client?: {
              /**
               * Image
               */
              image?: string;
              /**
               * Link
               */
              link?: {
                title?: string;
                url?: string;
                /**
                 * Anchor target (e.g. _blank). May be empty.
                 */
                target?: string;
              };
            }[];
            /**
             * Slider
             */
            slider?: "no" | "yes";
          }
        | {
            /**
             * Case studies
             */
            acf_fc_layout: "case-studies";
            /**
             * Case
             */
            case?: {
              /**
               * Image
               */
              image?: {
                ID?: number;
                id?: number;
                url?: string;
                alt?: string;
                title?: string;
                caption?: string;
                description?: string;
                filename?: string;
                mime_type?: string;
                width?: number;
                height?: number;
                /**
                 * Map of registered image-size slug -> URL (and -width / -height keys per size).
                 */
                sizes?: {
                  [k: string]: unknown;
                };
                [k: string]: unknown;
              };
              /**
               * Text top
               */
              text_top?: string;
              /**
               * Title
               */
              title?: string;
              /**
               * Description
               */
              description?: string;
              /**
               * Link
               */
              link?: {
                title?: string;
                url?: string;
                /**
                 * Anchor target (e.g. _blank). May be empty.
                 */
                target?: string;
              };
            }[];
            /**
             * Link
             */
            link?: {
              title?: string;
              url?: string;
              /**
               * Anchor target (e.g. _blank). May be empty.
               */
              target?: string;
            };
          }
        | {
            /**
             * Core Values
             */
            acf_fc_layout: "core-values";
            /**
             * Title
             */
            title?: string;
            /**
             * Core Value
             */
            core_value?: {
              /**
               * Title
               */
              title?: string;
              /**
               * Image
               */
              image?: string;
            }[];
          }
        | {
            /**
             * Team
             */
            acf_fc_layout: "team";
            /**
             * Title
             */
            title?: string;
            /**
             * Persons
             */
            persons?: {
              ID?: number;
              post_title?: string;
              /**
               * URL slug.
               */
              post_name?: string;
              post_type?: string;
              /**
               * WP-format datetime; not RFC3339.
               */
              post_date?: string;
              post_status?: string;
              [k: string]: unknown;
            }[];
          }
        | {
            /**
             * Our publications
             */
            acf_fc_layout: "our-publications";
            /**
             * Awards
             */
            awards?: {
              /**
               * Title
               */
              title?: string;
              /**
               * Awards
               */
              content?: string;
            };
            /**
             * PUBLICATIONS
             */
            publications?: {
              /**
               * Title
               */
              title?: string;
              /**
               * PUBLICATIONS
               */
              content?: string;
            };
            /**
             * ARTICLES & FEATURES
             */
            "articles_&_features"?: {
              /**
               * Title
               */
              title?: string;
              /**
               * ARTICLES & FEATURES
               */
              content?: string;
            };
          }
        | {
            /**
             * Expertise
             */
            acf_fc_layout: "expertise";
            /**
             * Title
             */
            title?: string;
            /**
             * Block
             */
            block?: {
              /**
               * Icon
               */
              icon?: {
                ID?: number;
                id?: number;
                url?: string;
                alt?: string;
                title?: string;
                caption?: string;
                description?: string;
                filename?: string;
                mime_type?: string;
                width?: number;
                height?: number;
                /**
                 * Map of registered image-size slug -> URL (and -width / -height keys per size).
                 */
                sizes?: {
                  [k: string]: unknown;
                };
                [k: string]: unknown;
              };
              /**
               * Title
               */
              title?: string;
              /**
               * Description
               */
              description?: string;
            }[];
            /**
             * Link
             */
            link?: {
              title?: string;
              url?: string;
              /**
               * Anchor target (e.g. _blank). May be empty.
               */
              target?: string;
            };
          }
        | {
            /**
             * Mobile pages
             */
            acf_fc_layout: "mobile-pages";
            /**
             * Images
             */
            images?: {
              /**
               * Image
               */
              image?: {
                ID?: number;
                id?: number;
                url?: string;
                alt?: string;
                title?: string;
                caption?: string;
                description?: string;
                filename?: string;
                mime_type?: string;
                width?: number;
                height?: number;
                /**
                 * Map of registered image-size slug -> URL (and -width / -height keys per size).
                 */
                sizes?: {
                  [k: string]: unknown;
                };
                [k: string]: unknown;
              };
            }[];
          }
        | {
            /**
             * Our Work
             */
            acf_fc_layout: "our-work";
            /**
             * Background color
             */
            background_color?: "default" | "linear-gradient-dribbble" | "white";
            name_group?: {
              /**
               * Name
               */
              name?: string;
              /**
               * Color
               */
              color?: string;
            };
            /**
             * Title
             */
            title?: string;
            /**
             * Description
             */
            description?: string;
            /**
             * Link
             */
            link?: {
              title?: string;
              url?: string;
              /**
               * Anchor target (e.g. _blank). May be empty.
               */
              target?: string;
            };
            /**
             * Image
             */
            image?: {
              ID?: number;
              id?: number;
              url?: string;
              alt?: string;
              title?: string;
              caption?: string;
              description?: string;
              filename?: string;
              mime_type?: string;
              width?: number;
              height?: number;
              /**
               * Map of registered image-size slug -> URL (and -width / -height keys per size).
               */
              sizes?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            /**
             * Column reverse
             */
            column_reverse?: "no" | "yes";
          }
        | {
            /**
             * Instagram
             */
            acf_fc_layout: "instagram";
          }
      )[];
    };
  } | null;
}

// jab/get-our-work — Get Our Work
/** Retrieves entries from the our work post type as id, title, excerpt, date, slug, link, and (when ACF fields apply) acf. */
export interface GetOurWorkInput {
  /**
   * Number of our work to return.
   */
  numberposts?: number;
  /**
   * Post status filter.
   */
  post_status?: "publish" | "draft" | "any";
}

export interface GetOurWorkOutput {
  our_work: {
    id: number;
    title: string;
    excerpt: string;
    /**
     * Published date in RFC3339 (UTC).
     */
    date: string;
    slug: string;
    link: string;
    featured_image: {
      ID: number;
      url: string;
      alt: string;
      width: number;
      height: number;
    } | null;
    "expertise-tag": {
      id: number;
      name: string;
      slug: string;
      description: string;
      count: number;
      /**
       * 0 for top-level terms; parent term_id otherwise.
       */
      parent_id: number;
    }[];
    work: {
      id: number;
      name: string;
      slug: string;
      description: string;
      count: number;
      /**
       * 0 for top-level terms; parent term_id otherwise.
       */
      parent_id: number;
    }[];
    acf: {
      /**
       * Blocks
       */
      template_part?: (
        | {
            /**
             * Header
             */
            acf_fc_layout: "header-single-work";
            /**
             * Title
             */
            title?: string;
            /**
             * Link
             */
            links?: {
              /**
               * Link
               */
              link?: {
                title?: string;
                url?: string;
                /**
                 * Anchor target (e.g. _blank). May be empty.
                 */
                target?: string;
              };
            }[];
          }
        | {
            /**
             * Two columns
             */
            acf_fc_layout: "two-columns-single-work";
            /**
             * Title
             */
            title?: string;
            /**
             * Description
             */
            description?: string;
          }
        | {
            /**
             * Views device
             */
            acf_fc_layout: "views-device-single-work";
            /**
             * Computer
             */
            computer?: {
              ID?: number;
              id?: number;
              url?: string;
              alt?: string;
              title?: string;
              caption?: string;
              description?: string;
              filename?: string;
              mime_type?: string;
              width?: number;
              height?: number;
              /**
               * Map of registered image-size slug -> URL (and -width / -height keys per size).
               */
              sizes?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            /**
             * Tablet
             */
            tablet?: {
              ID?: number;
              id?: number;
              url?: string;
              alt?: string;
              title?: string;
              caption?: string;
              description?: string;
              filename?: string;
              mime_type?: string;
              width?: number;
              height?: number;
              /**
               * Map of registered image-size slug -> URL (and -width / -height keys per size).
               */
              sizes?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            /**
             * Mobile
             */
            mobile?: {
              ID?: number;
              id?: number;
              url?: string;
              alt?: string;
              title?: string;
              caption?: string;
              description?: string;
              filename?: string;
              mime_type?: string;
              width?: number;
              height?: number;
              /**
               * Map of registered image-size slug -> URL (and -width / -height keys per size).
               */
              sizes?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
          }
        | {
            /**
             * Columns
             */
            acf_fc_layout: "columns-single-work";
            /**
             * Column
             */
            column?: {
              /**
               * name
               */
              name?: string;
              /**
               * title
               */
              title?: string;
              /**
               * description
               */
              description?: string;
            }[];
          }
        | {
            /**
             * Full image
             */
            acf_fc_layout: "full-image-single-work";
            /**
             * Image
             */
            image?: string;
          }
        | {
            /**
             * Block text
             */
            acf_fc_layout: "text-bock-single-work";
            /**
             * name
             */
            name?: string;
            /**
             * title
             */
            title?: string;
            /**
             * description
             */
            description?: string;
            /**
             * width
             */
            width?: number;
          }
        | {
            /**
             * Mobile pages
             */
            acf_fc_layout: "mobile-pages-single-work";
            /**
             * Images
             */
            images?: {
              /**
               * Image
               */
              image?: {
                ID?: number;
                id?: number;
                url?: string;
                alt?: string;
                title?: string;
                caption?: string;
                description?: string;
                filename?: string;
                mime_type?: string;
                width?: number;
                height?: number;
                /**
                 * Map of registered image-size slug -> URL (and -width / -height keys per size).
                 */
                sizes?: {
                  [k: string]: unknown;
                };
                [k: string]: unknown;
              };
            }[];
          }
        | {
            /**
             * Desktop pages
             */
            acf_fc_layout: "desktop-pages";
            /**
             * Nav Bar
             */
            nav_bar?: "black-nav-bar" | "silver-nav-bar";
            /**
             * Full width
             */
            full_width?: string;
            /**
             * First page
             */
            first_page?: string;
            /**
             * Second page
             */
            second_page?: string;
            /**
             * Automatic alignment
             */
            automatic_alignment?: "yes" | "no";
          }
        | {
            /**
             * Contact form
             */
            acf_fc_layout: "contact-form";
            /**
             * Title
             */
            title?: string;
            /**
             * Subtitle
             */
            subtitle?: string;
            /**
             * Background color
             */
            background_color?: "linear-gradient" | "color";
            /**
             * Text befor contact form
             */
            text_befor_contact_form?: string;
            /**
             * Display form?
             */
            "display_form?"?: "no" | "yes";
            /**
             * Phone
             */
            phone?: string;
            /**
             * Email
             */
            email?: string;
            /**
             * Testimonials
             */
            testimonials?: {
              ID?: number;
              post_title?: string;
              /**
               * URL slug.
               */
              post_name?: string;
              post_type?: string;
              /**
               * WP-format datetime; not RFC3339.
               */
              post_date?: string;
              post_status?: string;
              [k: string]: unknown;
            }[];
          }
        | {
            /**
             * Subscription form
             */
            acf_fc_layout: "subscription-form";
            /**
             * Title
             */
            title?: string;
            /**
             * Subtitle
             */
            subtitle?: string;
            /**
             * Form ( shortcode )
             */
            form?: string;
            /**
             * Background img
             */
            subscription_form_background_img?: string;
            /**
             * Video ( webm )
             */
            subscription_form_video_webm?: string;
            /**
             * Video ( mp4 )
             */
            subscription_form_video_mp4?: string;
          }
        | {
            /**
             * Slider
             */
            acf_fc_layout: "slider";
            /**
             * Images
             */
            images?: {
              /**
               * Image
               */
              image?: string;
            }[];
          }
        | {
            /**
             * Similar work
             */
            acf_fc_layout: "similar-work";
          }
        | {
            /**
             * Our Work
             */
            acf_fc_layout: "our-work";
            /**
             * Name Group
             */
            name_group?: {
              /**
               * Title
               */
              name?: string;
              /**
               * Color
               */
              color?: string;
            };
            /**
             * Title
             */
            title?: string;
            /**
             * Description
             */
            description?: string;
            /**
             * Link
             */
            link?: {
              title?: string;
              url?: string;
              /**
               * Anchor target (e.g. _blank). May be empty.
               */
              target?: string;
            };
            /**
             * Image
             */
            image?: {
              ID?: number;
              id?: number;
              url?: string;
              alt?: string;
              title?: string;
              caption?: string;
              description?: string;
              filename?: string;
              mime_type?: string;
              width?: number;
              height?: number;
              /**
               * Map of registered image-size slug -> URL (and -width / -height keys per size).
               */
              sizes?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            /**
             * Column reverse
             */
            column_reverse?: "no" | "yes";
            /**
             * Background color
             */
            background_color?: "default" | "linear-gradient-dribbble" | "white";
          }
        | {
            /**
             * Slider (two slides on the screen)
             */
            acf_fc_layout: "slider_two_slides";
            /**
             * Images
             */
            images?: {
              ID?: number;
              id?: number;
              url?: string;
              alt?: string;
              title?: string;
              caption?: string;
              description?: string;
              filename?: string;
              mime_type?: string;
              width?: number;
              height?: number;
              /**
               * Map of registered image-size slug -> URL (and -width / -height keys per size).
               */
              sizes?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            }[];
          }
        | {
            /**
             * Gallery
             */
            acf_fc_layout: "gallery";
            /**
             * images
             */
            images?: {
              ID?: number;
              id?: number;
              url?: string;
              alt?: string;
              title?: string;
              caption?: string;
              description?: string;
              filename?: string;
              mime_type?: string;
              width?: number;
              height?: number;
              /**
               * Map of registered image-size slug -> URL (and -width / -height keys per size).
               */
              sizes?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            }[];
          }
        | {
            /**
             * Contact Form Global
             */
            acf_fc_layout: "contact-form-global";
          }
        | {
            /**
             * Subscription Form Global
             */
            acf_fc_layout: "subscription-form-global";
          }
      )[];
    };
  }[];
}

// jab/get-works-by-slug — Get Our Work By Slug
/** Retrieves a single our work by its slug. Returns the same per-item shape as the list ability for this post type, or null when nothing matches. */
export interface GetWorksBySlugInput {
  /**
   * Slug of the our work to retrieve.
   */
  slug: string;
  /**
   * Post status filter.
   */
  post_status?: "publish" | "draft" | "any";
}

export interface GetWorksBySlugOutput {
  our_work: {
    id: number;
    title: string;
    excerpt: string;
    /**
     * Published date in RFC3339 (UTC).
     */
    date: string;
    slug: string;
    link: string;
    featured_image: {
      ID: number;
      url: string;
      alt: string;
      width: number;
      height: number;
    } | null;
    "expertise-tag": {
      id: number;
      name: string;
      slug: string;
      description: string;
      count: number;
      /**
       * 0 for top-level terms; parent term_id otherwise.
       */
      parent_id: number;
    }[];
    work: {
      id: number;
      name: string;
      slug: string;
      description: string;
      count: number;
      /**
       * 0 for top-level terms; parent term_id otherwise.
       */
      parent_id: number;
    }[];
    acf: {
      /**
       * Blocks
       */
      template_part?: (
        | {
            /**
             * Header
             */
            acf_fc_layout: "header-single-work";
            /**
             * Title
             */
            title?: string;
            /**
             * Link
             */
            links?: {
              /**
               * Link
               */
              link?: {
                title?: string;
                url?: string;
                /**
                 * Anchor target (e.g. _blank). May be empty.
                 */
                target?: string;
              };
            }[];
          }
        | {
            /**
             * Two columns
             */
            acf_fc_layout: "two-columns-single-work";
            /**
             * Title
             */
            title?: string;
            /**
             * Description
             */
            description?: string;
          }
        | {
            /**
             * Views device
             */
            acf_fc_layout: "views-device-single-work";
            /**
             * Computer
             */
            computer?: {
              ID?: number;
              id?: number;
              url?: string;
              alt?: string;
              title?: string;
              caption?: string;
              description?: string;
              filename?: string;
              mime_type?: string;
              width?: number;
              height?: number;
              /**
               * Map of registered image-size slug -> URL (and -width / -height keys per size).
               */
              sizes?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            /**
             * Tablet
             */
            tablet?: {
              ID?: number;
              id?: number;
              url?: string;
              alt?: string;
              title?: string;
              caption?: string;
              description?: string;
              filename?: string;
              mime_type?: string;
              width?: number;
              height?: number;
              /**
               * Map of registered image-size slug -> URL (and -width / -height keys per size).
               */
              sizes?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            /**
             * Mobile
             */
            mobile?: {
              ID?: number;
              id?: number;
              url?: string;
              alt?: string;
              title?: string;
              caption?: string;
              description?: string;
              filename?: string;
              mime_type?: string;
              width?: number;
              height?: number;
              /**
               * Map of registered image-size slug -> URL (and -width / -height keys per size).
               */
              sizes?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
          }
        | {
            /**
             * Columns
             */
            acf_fc_layout: "columns-single-work";
            /**
             * Column
             */
            column?: {
              /**
               * name
               */
              name?: string;
              /**
               * title
               */
              title?: string;
              /**
               * description
               */
              description?: string;
            }[];
          }
        | {
            /**
             * Full image
             */
            acf_fc_layout: "full-image-single-work";
            /**
             * Image
             */
            image?: string;
          }
        | {
            /**
             * Block text
             */
            acf_fc_layout: "text-bock-single-work";
            /**
             * name
             */
            name?: string;
            /**
             * title
             */
            title?: string;
            /**
             * description
             */
            description?: string;
            /**
             * width
             */
            width?: number;
          }
        | {
            /**
             * Mobile pages
             */
            acf_fc_layout: "mobile-pages-single-work";
            /**
             * Images
             */
            images?: {
              /**
               * Image
               */
              image?: {
                ID?: number;
                id?: number;
                url?: string;
                alt?: string;
                title?: string;
                caption?: string;
                description?: string;
                filename?: string;
                mime_type?: string;
                width?: number;
                height?: number;
                /**
                 * Map of registered image-size slug -> URL (and -width / -height keys per size).
                 */
                sizes?: {
                  [k: string]: unknown;
                };
                [k: string]: unknown;
              };
            }[];
          }
        | {
            /**
             * Desktop pages
             */
            acf_fc_layout: "desktop-pages";
            /**
             * Nav Bar
             */
            nav_bar?: "black-nav-bar" | "silver-nav-bar";
            /**
             * Full width
             */
            full_width?: string;
            /**
             * First page
             */
            first_page?: string;
            /**
             * Second page
             */
            second_page?: string;
            /**
             * Automatic alignment
             */
            automatic_alignment?: "yes" | "no";
          }
        | {
            /**
             * Contact form
             */
            acf_fc_layout: "contact-form";
            /**
             * Title
             */
            title?: string;
            /**
             * Subtitle
             */
            subtitle?: string;
            /**
             * Background color
             */
            background_color?: "linear-gradient" | "color";
            /**
             * Text befor contact form
             */
            text_befor_contact_form?: string;
            /**
             * Display form?
             */
            "display_form?"?: "no" | "yes";
            /**
             * Phone
             */
            phone?: string;
            /**
             * Email
             */
            email?: string;
            /**
             * Testimonials
             */
            testimonials?: {
              ID?: number;
              post_title?: string;
              /**
               * URL slug.
               */
              post_name?: string;
              post_type?: string;
              /**
               * WP-format datetime; not RFC3339.
               */
              post_date?: string;
              post_status?: string;
              [k: string]: unknown;
            }[];
          }
        | {
            /**
             * Subscription form
             */
            acf_fc_layout: "subscription-form";
            /**
             * Title
             */
            title?: string;
            /**
             * Subtitle
             */
            subtitle?: string;
            /**
             * Form ( shortcode )
             */
            form?: string;
            /**
             * Background img
             */
            subscription_form_background_img?: string;
            /**
             * Video ( webm )
             */
            subscription_form_video_webm?: string;
            /**
             * Video ( mp4 )
             */
            subscription_form_video_mp4?: string;
          }
        | {
            /**
             * Slider
             */
            acf_fc_layout: "slider";
            /**
             * Images
             */
            images?: {
              /**
               * Image
               */
              image?: string;
            }[];
          }
        | {
            /**
             * Similar work
             */
            acf_fc_layout: "similar-work";
          }
        | {
            /**
             * Our Work
             */
            acf_fc_layout: "our-work";
            /**
             * Name Group
             */
            name_group?: {
              /**
               * Title
               */
              name?: string;
              /**
               * Color
               */
              color?: string;
            };
            /**
             * Title
             */
            title?: string;
            /**
             * Description
             */
            description?: string;
            /**
             * Link
             */
            link?: {
              title?: string;
              url?: string;
              /**
               * Anchor target (e.g. _blank). May be empty.
               */
              target?: string;
            };
            /**
             * Image
             */
            image?: {
              ID?: number;
              id?: number;
              url?: string;
              alt?: string;
              title?: string;
              caption?: string;
              description?: string;
              filename?: string;
              mime_type?: string;
              width?: number;
              height?: number;
              /**
               * Map of registered image-size slug -> URL (and -width / -height keys per size).
               */
              sizes?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            /**
             * Column reverse
             */
            column_reverse?: "no" | "yes";
            /**
             * Background color
             */
            background_color?: "default" | "linear-gradient-dribbble" | "white";
          }
        | {
            /**
             * Slider (two slides on the screen)
             */
            acf_fc_layout: "slider_two_slides";
            /**
             * Images
             */
            images?: {
              ID?: number;
              id?: number;
              url?: string;
              alt?: string;
              title?: string;
              caption?: string;
              description?: string;
              filename?: string;
              mime_type?: string;
              width?: number;
              height?: number;
              /**
               * Map of registered image-size slug -> URL (and -width / -height keys per size).
               */
              sizes?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            }[];
          }
        | {
            /**
             * Gallery
             */
            acf_fc_layout: "gallery";
            /**
             * images
             */
            images?: {
              ID?: number;
              id?: number;
              url?: string;
              alt?: string;
              title?: string;
              caption?: string;
              description?: string;
              filename?: string;
              mime_type?: string;
              width?: number;
              height?: number;
              /**
               * Map of registered image-size slug -> URL (and -width / -height keys per size).
               */
              sizes?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            }[];
          }
        | {
            /**
             * Contact Form Global
             */
            acf_fc_layout: "contact-form-global";
          }
        | {
            /**
             * Subscription Form Global
             */
            acf_fc_layout: "subscription-form-global";
          }
      )[];
    };
  } | null;
}

// jab/get-categories — Get Categories
/** Retrieves all categories as a flat list of term objects. */
export interface GetCategoriesInput {
  /**
   * Exclude terms with no published posts.
   */
  hide_empty?: boolean;
  /**
   * Maximum number of terms to return.
   */
  number?: number;
}

export interface GetCategoriesOutput {
  categories: {
    id: number;
    name: string;
    slug: string;
    description: string;
    count: number;
    /**
     * 0 for top-level terms; parent term_id otherwise.
     */
    parent_id: number;
  }[];
}

// jab/get-tags — Get Tags
/** Retrieves all tags as a flat list of term objects. */
export interface GetTagsInput {
  /**
   * Exclude terms with no published posts.
   */
  hide_empty?: boolean;
  /**
   * Maximum number of terms to return.
   */
  number?: number;
}

export interface GetTagsOutput {
  tags: {
    id: number;
    name: string;
    slug: string;
    description: string;
    count: number;
    /**
     * 0 for top-level terms; parent term_id otherwise.
     */
    parent_id: number;
  }[];
}

// jab/get-expertise-tags — Get Expertise Tags
/** Retrieves all expertise tags as a flat list of term objects. */
export interface GetExpertiseTagsInput {
  /**
   * Exclude terms with no published posts.
   */
  hide_empty?: boolean;
  /**
   * Maximum number of terms to return.
   */
  number?: number;
}

export interface GetExpertiseTagsOutput {
  expertise_tags: {
    id: number;
    name: string;
    slug: string;
    description: string;
    count: number;
    /**
     * 0 for top-level terms; parent term_id otherwise.
     */
    parent_id: number;
  }[];
}

// jab/get-work-type — Get Work Type
/** Retrieves all work type as a flat list of term objects. */
export interface GetWorkTypeInput {
  /**
   * Exclude terms with no published posts.
   */
  hide_empty?: boolean;
  /**
   * Maximum number of terms to return.
   */
  number?: number;
}

export interface GetWorkTypeOutput {
  work_type: {
    id: number;
    name: string;
    slug: string;
    description: string;
    count: number;
    /**
     * 0 for top-level terms; parent term_id otherwise.
     */
    parent_id: number;
  }[];
}

// jab/get-menus — Get Nav Menus
/** Returns every registered WordPress nav menu with its items as a flat list and the theme locations each menu is assigned to. Items carry parent_id so consumers can rebuild the tree client-side. */
export interface GetMenusInput {}

export interface GetMenusOutput {
  menus: {
    id: number;
    slug: string;
    name: string;
    /**
     * Theme-registered menu locations (e.g. "primary", "footer") this menu is assigned to.
     */
    locations: string[];
    /**
     * Flat list of menu items. Use parent_id to reconstruct the tree.
     */
    items: {
      id: number;
      title: string;
      url: string;
      /**
       * Link target. Empty string for same-window, "_blank" for new window.
       */
      target: string;
      /**
       * WP object kind: "post", "page", "category", "custom", etc.
       */
      object_type: string;
      /**
       * ID of the linked WP object, when applicable. 0 for custom URLs.
       */
      object_id: number;
      /**
       * ID of the parent menu item. 0 for top-level items.
       */
      parent_id: number;
      /**
       * Item order within its parent.
       */
      order: number;
    }[];
  }[];
}

